### PR TITLE
enh(UI): replacing select with select2

### PR DESCRIPTION
**Pull request by sc979**
resolve: MON-3319

### CODE REVIEW

**Comment by sc979** [comment]
linked to  :
https://github.com/centreon/centreon/pull/7119

**Comment by CPbN** [comment]
Hi @sc979,

I'm not sure multi hostgroup selection works, my selection field remains empty, it does not show the existing hostgroups, I then can't filter on one of them.

ANy remaining issue perhaps ?

Thank you !

Screen Shot 2019-04-01 at 13 46 39

**Comment by CPbN** [comment]
Issue seems to come from the field name :

Screen Shot 2019-04-01 at 14 13 13

If I replace `param_23[]` by `param_23` (directly in the browser) then I can at least manually enter a hostgroup name, which is then correctly saved.

**Comment by sc979** [comment]
Hi CPbN,

Thanks for your feedback.

The text " Hostgroup" is only displayed in the field before you choose any hostgroup(s), or when you empty it. It isn't linked to anything.

As the select2 call an API to retrieve the available hostgroups, please can you check that you also applied the code from the PR linked : https://github.com/centreon/centreon/pull/7119

Regards,

sc979

**Comment by sc979** [comment]
image

Can you share your PHP and SQL logs please :
`/var/log/centreon/sql-error.log`
`/var/opt/rh/rh-php71/log/php-fpm/centreon-error.log`

**Comment by CPbN** [comment]
Thank you for your response @sc979.

"HostGroup" text is highlighted above in my screenshot, but I speak about 2 lines below, the select field with name `param_23[]`.

The PR you link is applied yes, as I run last released versions (Centreon 18.10.4 and widget 18.10.2).

**Comment by CPbN** [comment]
> Can you share your PHP and SQL logs please :
> `/var/log/centreon/sql-error.log`
> `/var/opt/rh/rh-php71/log/php-fpm/centreon-error.log`

There are no particular errors in these logs, let me uninstall / reinstall / reconfigure the widget to see if this triggers some errors.

**Comment by CPbN** [comment]
No, no error in the logs...
What is strange is that when I save widget preferences, the hostgroup parameter is not recorded into `widget_preferences` table (look at missing field 131) :
```
MariaDB [centreon]> select * from widget_preferences;
+----------------+--------------+-----------------------+---------+
| widget_view_id | parameter_id | preference_value      | user_id |
+----------------+--------------+-----------------------+---------+
(...)
|             24 |          116 |                       |      19 |
|             24 |          117 |                       |      19 |
|             24 |          118 | 0                     |      19 |
|             24 |          119 | 0                     |      19 |
|             24 |          120 | 0                     |      19 |
|             24 |          121 | 1                     |      19 |
|             24 |          122 | 1                     |      19 |
|             24 |          123 | 1                     |      19 |
|             24 |          124 | 1                     |      19 |
|             24 |          125 |                       |      19 |
|             24 |          126 |                       |      19 |
|             24 |          127 |                       |      19 |
|             24 |          128 |                       |      19 |
|             24 |          129 |                       |      19 |
|             24 |          130 |                       |      19 |
|             24 |          132 |                       |      19 |
|             24 |          133 | 10                    |      19 |
|             24 |          134 |                       |      19 |
|             24 |          135 | 1                     |      19 |
|             24 |          136 | 1                     |      19 |
|             24 |          137 | 0                     |      19 |
|             24 |          138 | 1                     |      19 |
|             24 |          139 | 1                     |      19 |
|             24 |          140 | 50                    |      19 |
|             24 |          141 | 1                     |      19 |
|             24 |          142 | 1                     |      19 |
|             24 |          143 | 1                     |      19 |
|             24 |          144 | 1                     |      19 |
|             24 |          145 | 1                     |      19 |
|             24 |          146 | 0                     |      19 |
|             24 |          147 | 0                     |      19 |
|             24 |          148 | 0                     |      19 |
|             24 |          149 | 50                    |      19 |
|             24 |          150 | last_state_change ASC |      19 |
|             24 |          151 |                       |      19 |
|             24 |          152 | 30                    |      19 |
|             24 |          153 | 0                     |      19 |
+----------------+--------------+-----------------------+---------+
```

**Comment by CPbN** [comment]
Well I can manually enter a groupname without having to update the fieldname...
Field is then correctly recognized, and saved.
But still no dropdown.

**Comment by CPbN** [comment]
The following URL is correctly called when I click into the Hostgroup field :
`/centreon/include/common/webServices/rest/internal.php?object=centreon_configuration_hostgroup&action=list&page_limit=60&page=1`
And a correct JSON result is returned, containing my hostgroups...
In addition, no javascript error in the browser console.

**Comment by CPbN** [comment]
I've found the culprit @sc979 
https://github.com/centreon/centreon/pull/7119/files#diff-123c19b6453914632e335ab166052384
If I set z-index to 1065, then it works. Values below do not work. Above of course do.

**Comment by sc979** [comment]
Sorry for the delay,

I had to achieve my task and open the PR first... I began to investigate and found that in the mysql results screenshot, you need to search for "parameter_id" = 23, as it's this value that is displayed in the front screenshot send previously.

For the z-index, I didn't talk about it, as you told me that the code of the linked PR (#7119) was already applied on your platform

I'm glad you fixed your widget

**Comment by CPbN** [comment]
Don't worry, thank you for your answer.

Yes PR #7119 is applied yes.
But I have to increase the value (you already increased from 1051 to 161) from 1061 to 1065.

**Comment by sc979** [comment]
Then, I'll increase the z-index value.

**Comment by CPbN** [comment]
OK :)
Many thanks @sc979 👍

**Comment by sc979** [comment]
I merged the fix ;)

**Comment by CPbN** [comment]
Excellent, thank you again :)

**Pull request merged**
